name: Install Python, pipenv and Pipfile packages
description: Install Python, pipenv and Pipfile packages

inputs:
  python-version:
    description: The version of Python to use
    required: true

runs:
  using: "composite"
  steps:
    - id: setup-python
      name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pipenv'

    - id: install-pipenv
      name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      shell: bash

    - id: sync-pipfile
      name: Sync Pipfile
      run: pipenv sync --dev --python ${{ inputs.python-version }}
      shell: bash
